<?php

namespace Container68HPxcv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLecon2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JmqEM1n.App\Entity\Lecon' shared service.
     *
     * @return \App\Entity\Lecon
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.JmqEM1n": it needs an instance of "App\\Entity\\Lecon" but this type has been excluded in "config/services.yaml".');
    }
}
