<?php

namespace ContainerBRlZgdG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RPk59qIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rPk59qI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rPk59qI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formationRepository' => ['privates', 'App\\Repository\\FormationRepository', 'getFormationRepositoryService', true],
            'formationScoreRepository' => ['privates', 'App\\Repository\\FormationScoreRepository', 'getFormationScoreRepositoryService', true],
        ], [
            'formationRepository' => 'App\\Repository\\FormationRepository',
            'formationScoreRepository' => 'App\\Repository\\FormationScoreRepository',
        ]);
    }
}
