<?php

namespace ContainerOPj1QaA;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NzhlhZpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NzhlhZp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NzhlhZp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'leconRepository' => ['privates', 'App\\Repository\\LeconRepository', 'getLeconRepositoryService', true],
        ], [
            'leconRepository' => 'App\\Repository\\LeconRepository',
        ]);
    }
}
