knp_paginator:
    page_range: 5  # Number of page links shown
    default_options:
        page_name: page  # Query parameter for page
        sort_field_name: sort  # For sorting (if used)
        sort_direction_name: direction  # For sorting direction (if used)
        distinct: true  # Ensure distinct results
        filter_field_name: filterField  # For filtering (if used)
        filter_value_name: filterValue  # For filtering (if used)
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'  # Default Bootstrap 5 template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'  # If you add sorting
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # If you add filtering