framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
# framework:
#     default_locale: fr  # Définir la locale par défaut sur 'fr'
#     translator:
#         default_path: '%kernel.project_dir%/translations'
#         fallbacks:
#   