vich_uploader:
    db_driver: orm
    mappings:
        formation_pdfs:
            uri_prefix: /uploads/formations
            upload_destination: '%kernel.project_dir%/public/uploads/lecons'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
