<?php

namespace ContainerWGOpklL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W0oRuw7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w0oRuw7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w0oRuw7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'apprenantRepository' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
            'inscriptionCoursRepository' => ['privates', 'App\\Repository\\InscriptionCoursRepository', 'getInscriptionCoursRepositoryService', true],
        ], [
            'apprenantRepository' => 'App\\Repository\\ApprenantRepository',
            'inscriptionCoursRepository' => 'App\\Repository\\InscriptionCoursRepository',
        ]);
    }
}
