<?php

namespace ContainerWGOpklL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D8zEG0QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D8zEG0Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D8zEG0Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lecon' => ['privates', '.errored..service_locator.D8zEG0Q.App\\Entity\\Lecon', NULL, 'Cannot autowire service ".service_locator.D8zEG0Q": it needs an instance of "App\\Entity\\Lecon" but this type has been excluded in "config/services.yaml".'],
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
        ], [
            'lecon' => 'App\\Entity\\Lecon',
            'pdfService' => 'App\\Service\\PdfService',
        ]);
    }
}
