<?php

namespace ContainerOsZL4Ji;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LnsowtiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lnsowti' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lnsowti'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formation' => ['privates', '.errored..service_locator.lnsowti.App\\Entity\\Formation', NULL, 'Cannot autowire service ".service_locator.lnsowti": it needs an instance of "App\\Entity\\Formation" but this type has been excluded in "config/services.yaml".'],
            'leconRepository' => ['privates', 'App\\Repository\\LeconRepository', 'getLeconRepositoryService', true],
        ], [
            'formation' => 'App\\Entity\\Formation',
            'leconRepository' => 'App\\Repository\\LeconRepository',
        ]);
    }
}
