<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Apprenant extends \App\Entity\Apprenant implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'avis' => [parent::class, 'avis', null],
        "\0".parent::class."\0".'email_apprenant' => [parent::class, 'email_apprenant', null],
        "\0".parent::class."\0".'niveau_etude' => [parent::class, 'niveau_etude', null],
        "\0".parent::class."\0".'nom_apprenant' => [parent::class, 'nom_apprenant', null],
        "\0".parent::class."\0".'prenom_apprenant' => [parent::class, 'prenom_apprenant', null],
        "\0".parent::class."\0".'progressions' => [parent::class, 'progressions', null],
        "\0".'App\\Entity\\User'."\0".'dateDeNaissance' => ['App\\Entity\\User', 'dateDeNaissance', null],
        "\0".'App\\Entity\\User'."\0".'email' => ['App\\Entity\\User', 'email', null],
        "\0".'App\\Entity\\User'."\0".'image' => ['App\\Entity\\User', 'image', null],
        "\0".'App\\Entity\\User'."\0".'nom' => ['App\\Entity\\User', 'nom', null],
        "\0".'App\\Entity\\User'."\0".'password' => ['App\\Entity\\User', 'password', null],
        "\0".'App\\Entity\\User'."\0".'prenom' => ['App\\Entity\\User', 'prenom', null],
        "\0".'App\\Entity\\User'."\0".'roles' => ['App\\Entity\\User', 'roles', null],
        'avis' => [parent::class, 'avis', null],
        'dateDeNaissance' => ['App\\Entity\\User', 'dateDeNaissance', null],
        'email' => ['App\\Entity\\User', 'email', null],
        'email_apprenant' => [parent::class, 'email_apprenant', null],
        'id' => [parent::class, 'id', null],
        'image' => ['App\\Entity\\User', 'image', null],
        'niveau_etude' => [parent::class, 'niveau_etude', null],
        'nom' => ['App\\Entity\\User', 'nom', null],
        'nom_apprenant' => [parent::class, 'nom_apprenant', null],
        'password' => ['App\\Entity\\User', 'password', null],
        'prenom' => ['App\\Entity\\User', 'prenom', null],
        'prenom_apprenant' => [parent::class, 'prenom_apprenant', null],
        'progressions' => [parent::class, 'progressions', null],
        'roles' => ['App\\Entity\\User', 'roles', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
