<?php

namespace ContainerDBVd8Di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OJoxC5dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oJoxC5d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oJoxC5d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pdf' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
        ], [
            'pdf' => 'App\\Service\\PdfService',
        ]);
    }
}
