<?php

namespace ContainerDBVd8Di;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JbpNamuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JbpNamu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JbpNamu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formation' => ['privates', '.errored..service_locator.JbpNamu.App\\Entity\\Formation', NULL, 'Cannot autowire service ".service_locator.JbpNamu": it needs an instance of "App\\Entity\\Formation" but this type has been excluded in "config/services.yaml".'],
            'inscriptionCoursRepository' => ['privates', 'App\\Repository\\InscriptionCoursRepository', 'getInscriptionCoursRepositoryService', true],
        ], [
            'formation' => 'App\\Entity\\Formation',
            'inscriptionCoursRepository' => 'App\\Repository\\InscriptionCoursRepository',
        ]);
    }
}
