<?php

namespace ContainerRkjihwg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YtbWktLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YtbWktL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YtbWktL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'inscriptionCour' => ['privates', '.errored..service_locator.YtbWktL.App\\Entity\\InscriptionCours', NULL, 'Cannot autowire service ".service_locator.YtbWktL": it needs an instance of "App\\Entity\\InscriptionCours" but this type has been excluded in "config/services.yaml".'],
        ], [
            'inscriptionCour' => 'App\\Entity\\InscriptionCours',
        ]);
    }
}
