<?php

namespace ContainerRkjihwg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SJArFDd.App\Entity\Message' shared service.
     *
     * @return \App\Entity\Message
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SJArFDd": it needs an instance of "App\\Entity\\Message" but this type has been excluded in "config/services.yaml".');
    }
}
