<?php

namespace ContainerVvLLc6c;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XUsTS7FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xUsTS7F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xUsTS7F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lecon' => ['privates', '.errored..service_locator.xUsTS7F.App\\Entity\\Lecon', NULL, 'Cannot autowire service ".service_locator.xUsTS7F": it needs an instance of "App\\Entity\\Lecon" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lecon' => 'App\\Entity\\Lecon',
        ]);
    }
}
