<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZQ3X81X/getEvenement2Service.php
namespace ContainerZQ3X81X;
========
namespace ContainerVvLLc6c;
>>>>>>>> 8611b6e672bfc92a3280990b1971f5e769fb70aa:var/cache/dev/ContainerVvLLc6c/getEvenement2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvenement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.td4zu.o.App\Entity\Evenement' shared service.
     *
     * @return \App\Entity\Evenement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.td4zu.o": it needs an instance of "App\\Entity\\Evenement" but this type has been excluded in "config/services.yaml".');
    }
}
