<?php

namespace ContainerF1LP4cG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dy6wSj2.App\Entity\Formation' shared service.
     *
     * @return \App\Entity\Formation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dy6wSj2": it needs an instance of "App\\Entity\\Formation" but this type has been excluded in "config/services.yaml".');
    }
}
