<?php

namespace ContainerZQ3X81X;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K_BttT5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k.bttT5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k.bttT5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'formation' => ['privates', '.errored..service_locator.k.bttT5.App\\Entity\\Formation', NULL, 'Cannot autowire service ".service_locator.k.bttT5": it needs an instance of "App\\Entity\\Formation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'formation' => 'App\\Entity\\Formation',
        ]);
    }
}
