<?php

namespace ContainerZQ3X81X;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XEtsAU1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xEtsAU1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xEtsAU1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formationRepository' => ['privates', 'App\\Repository\\FormationRepository', 'getFormationRepositoryService', true],
            'lecon' => ['privates', '.errored..service_locator.xEtsAU1.App\\Entity\\Lecon', NULL, 'Cannot autowire service ".service_locator.xEtsAU1": it needs an instance of "App\\Entity\\Lecon" but this type has been excluded in "config/services.yaml".'],
            'progressionRepository' => ['privates', 'App\\Repository\\ProgressionRepository', 'getProgressionRepositoryService', true],
        ], [
            'formationRepository' => 'App\\Repository\\FormationRepository',
            'lecon' => 'App\\Entity\\Lecon',
            'progressionRepository' => 'App\\Repository\\ProgressionRepository',
        ]);
    }
}
