<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZQ3X81X/getFormationService.php
namespace ContainerZQ3X81X;
========
namespace ContainerVvLLc6c;
>>>>>>>> 8611b6e672bfc92a3280990b1971f5e769fb70aa:var/cache/dev/ContainerVvLLc6c/getFormation2Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dy6wSj2.App\Entity\Formation' shared service.
     *
     * @return \App\Entity\Formation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dy6wSj2": it needs an instance of "App\\Entity\\Formation" but this type has been excluded in "config/services.yaml".');
    }
}
