<?php

<<<<<<<< HEAD:var/cache/dev/ContainerZQ3X81X/getFormationScoreServiceService.php
namespace ContainerZQ3X81X;
========
namespace ContainerVvLLc6c;
>>>>>>>> 8611b6e672bfc92a3280990b1971f5e769fb70aa:var/cache/dev/ContainerVvLLc6c/getFormationScoreServiceService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormationScoreServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FormationScoreService' shared autowired service.
     *
     * @return \App\Service\FormationScoreService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FormationScoreService.php';

        return $container->privates['App\\Service\\FormationScoreService'] = new \App\Service\FormationScoreService(($container->privates['App\\Repository\\FormationScoreRepository'] ?? $container->load('getFormationScoreRepositoryService')));
    }
}
