<?php

namespace Container1Gr5NfQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JmqEM1nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JmqEM1n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JmqEM1n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lecon' => ['privates', '.errored..service_locator.JmqEM1n.App\\Entity\\Lecon', NULL, 'Cannot autowire service ".service_locator.JmqEM1n": it needs an instance of "App\\Entity\\Lecon" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'lecon' => 'App\\Entity\\Lecon',
        ]);
    }
}
