<?php

namespace ContainerQ2yePTn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lv65OdcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lv65Odc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lv65Odc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formationRepository' => ['privates', 'App\\Repository\\FormationRepository', 'getFormationRepositoryService', true],
            'paginator' => ['privates', '.errored.UWzgNAI', NULL, 'Cannot determine controller argument for "App\\Controller\\FormationController::index()": the $paginator argument is type-hinted with the non-existent class or interface: "App\\Controller\\PaginatorInterface". Did you forget to add a use statement?'],
        ], [
            'formationRepository' => 'App\\Repository\\FormationRepository',
            'paginator' => '?',
        ]);
    }
}
