<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUQwQizJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUQwQizJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUQwQizJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUQwQizJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUQwQizJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'UQwQizJ',
    'container.build_id' => '1b1749fd',
    'container.build_time' => 1740370289,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUQwQizJ');
