<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container68HPxcv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container68HPxcv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container68HPxcv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container68HPxcv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container68HPxcv\App_KernelDevDebugContainer([
    'container.build_hash' => '68HPxcv',
    'container.build_id' => '04f93d08',
    'container.build_time' => 1740370743,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container68HPxcv');
