<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF1LP4cG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF1LP4cG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF1LP4cG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF1LP4cG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF1LP4cG\App_KernelDevDebugContainer([
    'container.build_hash' => 'F1LP4cG',
    'container.build_id' => 'a54d0f6c',
    'container.build_time' => 1740699664,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF1LP4cG');
